### ISSUE TITLE
Porting patches to Goptuna.

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna-dashboard#48]
## Motivation

The code base of optuna-dashboard is originally taken from [Goptuna](https://github.com/c-bata/goptuna) project.
But recently, following changes are added to optuna-dashboard by external contributors.

* https://github.com/optuna/optuna-dashboard/pull/34 by @2403hwaseer 
* https://github.com/optuna/optuna-dashboard/pull/41 by @zchenry 
* https://github.com/optuna/optuna-dashboard/pull/42 by @zchenry 
* https://github.com/optuna/optuna-dashboard/pull/44 (WIP) by @zchenry 

In this issue, I want to ask external contributors whether I can port these patches to [Goptuna](https://github.com/c-bata/goptuna).

@2403hwaseer @zchenry May I have your response?

## TODO

* [x] Agreement from @zchenry 
* [x] Agreement from @2403hwaseer 
* [ ] Add CLA (Contributor License Agreements) to port patches to Goptuna.

**Comment by 2403hwaseer** [comment]
@c-bata , I agree and would be really happy if the code gets used somewhere else too. Thank you!

**Comment by c-bata** [comment]
> @c-bata , I agree and would be really happy if the code gets used somewhere else too. Thank you!

Thank you for your agreement!

**Comment by zchenry** [comment]
@c-bata I agree and it's my pleasure to see my code being useful. Thank you!

**Comment by c-bata** [comment]
> @c-bata I agree and it's my pleasure to see my code being useful. Thank you!

Thank you!!
